name: Deploy to AWS EC2

on:
  workflow_run:
    workflows: ["Build & Push Docker Image"]  # ← nama workflow build-docker kamu yang sudah ada
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy via SSH ke EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 3.236.150.30 
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          port: 22
          script: |
            cd /home/ec2-user/pso-final-library-management   # 99% ini path kalian, coba dulu
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker compose down || true
            docker pull ghcr.io/arfi5026231119/pso-final-library-management:latest
            docker compose up -d
            docker system prune -f
            echo "🚀 DEPLOY SELESAI! Fitur baru sudah live di http://3.236.150.30"